name: Node.js testing

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        apiKey: ${{ secrets.postmanApiKey }}
        collection: 15378248-ece30070-deb3-410d-b1a0-fdec988fdeaf
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
